### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by glibersat** [h2mille/YaDoM#1]
Hello Hugo,

Nous sommes potentiellement intéressés pour la cofabrik, cependant, il n'y a pas de détail sur les licences. Nous aimerions avoir un système où nous ne sommes pas coincés en cas de disparition du concepteur.

Merci,

Guillaume,
pour la cofabrik

**Comment by h2mille** [comment]
Bonjour,
Je viens d'ajouter le fichier de license BSD3. Ce projet est libre et open-source. Si il est possible que le concepteur detruise les sources, ce qui ne devrait en aucune façon être le cas, il est tout à fait possible que vous en fassiez une copie avant.
Ce projet contient globalement du C, du python, du php et du sqlite, donc 4 techno qui sont particulièrement courantes dans le milieu de développeurs. Il peut être repris, amélioré, voir corrigé par n'importe quel développeur.
Tout le code source est libre, et donc si un prestataire vous proposait l'installation de ce projet, il peut vous facturer le temps d'installation, les mises à jour et adaptations, mais pas le logiciel fourni ici.
Utiliser du Logiciel libre est justement une bonne alternative à se retrouver coincé avec un unique prestataire, et avec un produit non évolutif.
Je me rends compte qu'il manque une partie du projet (génération et modification de la base python), j'upload ça sous peu.

**Comment by h2mille** [comment]
J'ai mis à jour les sources côté serveur, et ajouté pas mal d'explications dans les read-me
